App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^registe/$', views.registe, name='registe'),
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),
    url(r'changecartselect/$', views.changecartselect,name='changecartselect'),
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'^orderinfo/(\d+)/$', views.orderinfo, name='orderinfo'),
]

Axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('App.urls',namespace='App'))
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    {% block extcss %}

    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% block header %}
    <header>爱鲜蜂</header>
{% endblock %}

<div class="hidescroll">
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
</div>

{% block footer %}
    <footer>
        <a href="{% url 'App:index' %}" class="home">
            <dl>
                <dt> <span> </span> </dt>
                <dd>首页</dd>
            </dl>
        </a>

        <a href="{% url 'App:market' 104749 0 0 %}" class="market">
            <dl>
                <dt> <span> </span> </dt>
                <dd>闪购超市</dd>
            </dl>
        </a>

        <a href="{% url 'App:cart' %}" class="cart">
            <dl>
                <dt> <span> </span> </dt>
                <dd>购物车</dd>
            </dl>
        </a>

        <a href="{% url 'App:mine' %}" class="mine">
            <dl>
                <dt> <span> </span> </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}

</body>
<script src="{% static 'base/js/jquery.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="{% static 'base/js/swiper.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{% block extjs %}

{% endblock %}
</html>