App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^registe/$', views.registe, name='registe'),
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),
    url(r'changecartselect/$', views.changecartselect,name='changecartselect'),
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'^orderinfo/(\d+)/$', views.orderinfo, name='orderinfo'),
]

Axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('App.urls',namespace='App'))
]

App/models.py
from django.db import models

# Create your models here.
class Base(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=10)
    class Meta:
        abstract = True

class Wheel(Base):
    class Meta:
        db_table = 'axf_wheel'

class Nav(Base):
    class Meta:
        db_table = 'axf_nav'

class Mustbuy(Base):
    class Meta:
        db_table = 'axf_mustbuy'

class Shop(Base):
    class Meta:
        db_table = 'axf_shop'


class MainShow(models.Model):
    trackid = models.CharField(max_length=8)
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=100)
    brandname = models.CharField(max_length=50)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=8)
    productid1 = models.CharField(max_length=8)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField()
    marketprice1 = models.FloatField()

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=8)
    productid2 = models.CharField(max_length=8)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField()
    marketprice2 = models.FloatField()

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=8)
    productid3 = models.CharField(max_length=8)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField()
    marketprice3 = models.FloatField()

    class Meta:
        db_table = 'axf_mainshow'

class Foodtypes(models.Model):
    typeid = models.CharField(max_length=8)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=256)
    typesort = models.IntegerField()

    class Meta:
        db_table = 'axf_foodtypes'


class Goods(models.Model):
    productid = models.CharField(max_length=10)
    productimg = models.CharField(max_length=100)
    productname = models.CharField(max_length=100)
    productlongname = models.CharField(max_length=100)
    isxf = models.BooleanField(default=False)
    pmdesc = models.BooleanField(default=False)
    specifics = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    marketprice = models.DecimalField(max_digits=7,decimal_places=2)
    categoryid = models.IntegerField()
    childcid = models.IntegerField()
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=10)
    storenums = models.IntegerField()
    productnum = models.IntegerField()

    class Meta:
        db_table = 'axf_goods'


class User(models.Model):
    account = models.CharField(max_length=80, unique=True)
    password = models.CharField(max_length=256)
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=20, unique=True)
    addr = models.CharField(max_length=256)
    img = models.CharField(max_length=100)
    rank = models.IntegerField(default=1)
    token = models.CharField(max_length=256)

    class Meta:
        db_table = 'axf_user'


class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)

    class Meta:
        db_table = 'axf_cart'


class Order(models.Model):
    user = models.ForeignKey(User)
    createtime = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=1)
    identifier = models.CharField(max_length=256)

    class Meta:
        db_table = 'axf_order'


class OrderGoods(models.Model):
    order = models.ForeignKey(Order)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_orderGoods'

templates/order/orderinfo.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'order/css/orderinfo.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'order/js/orderinfo.js' %}"></script>
{% endblock %}

{% block title %}
    爱鲜蜂 | 订单详情
{% endblock %}

{% block content %}
<div class="orderinfo">
    <h3>订单号: {{ order.identifier }}</h3>
    <ul>
        {% for orderGoods in order.ordergoods_set.all %}
            <li>
                <div class="content-wrapper">
                    <div class="img">
                        <img src="{{ orderGoods.goods.productimg }}" alt="">
                    </div>
                    <div class="detail">
                        <p class="name">
                            {{ orderGoods.goods.productlongname }}
                        </p>
                        <p class="price">
                            ￥{{ orderGoods.goods.price }}
                        </p>
                        <p class="num">
                            x{{ orderGoods.number }}
                        </p>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>

    <div class="bill">
        <div class="bill-right" id="generateorder">
            <button class="btn btn-warning" id="pay" style="width: 60px;height: 30px">付款</button>
        </div>
    </div>
</div>
{% endblock %}