App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^registe/$', views.registe, name='registe'),
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^subcart/$', views.subcart, name='subcart'),
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),
    url(r'changecartselect/$', views.changecartselect,name='changecartselect'),
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    url(r'^orderinfo/(\d+)/$', views.orderinfo, name='orderinfo'),
]

Axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('App.urls',namespace='App'))
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}
{% block title %}
    爱鲜蜂 | 登录
{% endblock %}
{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'App:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>

        <form action="{% url 'App:login' %}" method="post">
            {% csrf_token %}
            {#            账号#}
            <div class="form-group has-feedback" id="account">
                <div class="input-group">
                    <div class="input-group-addon">账号</div>
                    <input type="text" class="form-control" placeholder="数字、字母" name="account" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i>{{ acountErr }}</i>
            </div>

            {#            密码#}
            <div class="form-group" id="password">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6~12位纯数字" name="password" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i>{{ passwdErr }}</i>
            </div>


{#            <input type="submit" id="subButton" value="登录">#}
            <div id="subButton" class="btn btn-default">
                登录
            </div>
        </form>
    </div>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}
{% block title %}
    爱鲜蜂 | 我的
{% endblock %}
{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="{{ img }}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <a href="{% url 'App:login' %}">
                        <span class="glyphicon glyphicon-user"></span>
                        {{ name }}
                    </a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-star "></span>
                    VIP: {{ rank | default:'暂无等级' }}
                </p>
                <a href="{% url 'App:registe' %}" class="register">注册</a>
            </div>
        </div>

        <div class="collect">
            <span class="glyphicon glyphicon-heart"></span>
            <span>收藏</span>
        </div>

        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="#">查看订单 <b class="glyphicon glyphicon-chevron-right"></b> </a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-piggy-bank"></dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-plane"></dt>
                                <dd>待收获</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-edit"></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-transfer"></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-gift"></dt>
                                <dd>优惠卷</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-globe"></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-phone-alt"></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="glyphicon glyphicon-king"></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section class="quit">
                <a href="/logout/">退出</a>
            </section>
        </div>
    </div>
{% endblock %}

templates/mine/registe.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/registe.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/registe.js' %}"></script>
{% endblock %}
{% block title %}
    爱鲜蜂 | 注册
{% endblock %}
{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'App:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
        <form action="{% url 'App:registe' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group has-feedback" id="account">
                <div class="input-group">
                    <div class="input-group-addon">账号</div>
                    <input type="text" class="form-control" placeholder="请输入数字或字母" name="account" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
            <div class="form-group" id="password">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="请输入6~12位密码" name="password" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
            <div class="form-group" id="passwd">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="请输入6~12位密码" name="passwd" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
            <div class="form-group" id="name">
                <div class="input-group">
                    <div class="input-group-addon">名字</div>
                    <input type="text" class="form-control" placeholder="昵称" name="name" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
            <div class="form-group" id="tel">
                <div class="input-group">
                    <div class="input-group-addon">手机</div>
                    <input type="text" class="form-control" placeholder="请输入手机号码" name="tel" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
            <div class="form-group" id="addr">
                <div class="input-group">
                    <div class="input-group-addon">地址</div>
                    <input type="text" class="form-control" placeholder="收货地址(默认选项)" name="addr" required="required">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">头像</div>
                    <input type="file" name="icon" required="required">
                </div>
            </div>
            <input type="submit" id="subButton" value="注册">
        </form>
    </div>
{% endblock %}